# Generated by Django 4.0.4 on 2023-05-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField(verbose_name='Почтовый индекс')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('city', models.CharField(max_length=256, verbose_name='Город')),
                ('state_name', models.CharField(max_length=256, verbose_name='Штат')),
                ('country_name', models.CharField(max_length=256, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Локация',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_weight', models.PositiveIntegerField(default=1, verbose_name='Вес груза')),
                ('cargo_description', models.TextField(max_length=2300, verbose_name='Описание груза')),
                ('location_delivery', models.ManyToManyField(related_name='сargo_location_delivery', to='api.location', verbose_name='Локация: куда доставить')),
                ('location_pickup', models.ManyToManyField(related_name='сargo_location_pickup', to='api.location', verbose_name='Локация: откуда забрать')),
            ],
            options={
                'verbose_name': 'Груз',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=124, verbose_name='Уникальный номер')),
                ('load_capacity', models.PositiveIntegerField(default=1, verbose_name='Грузоподъемность')),
                ('location', models.ManyToManyField(related_name='car_location', to='api.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Машина',
            },
        ),
    ]
